// 本文件由 scripts/generate-model-presets.mjs 生成（@earendil-works/pi-ai@0.85.1）。
// 单一事实来源是 pi-ai 内置 provider 目录：手改即破，升级后重跑 pnpm gen:model-presets。

export type ModelPreset = {
  /** pi-ai 内置目录的路由键：命中时 dsh 继承目录端点/协议/模型目录 */
  id: string;
  name: string;
  baseUrl: string;
  /** UI 三协议之一；null = 不预填（继承目录协议） */
  api: string | null;
  /** 目录模型数量（选择器副行展示） */
  models: number;
  /** pi-ai 同版本内置目录模型 id，保持上游目录顺序；仅供继承目录选择，不写回 settings.yaml */
  modelIds: string[];
};

export const MODEL_PRESETS: ModelPreset[] = [
  {
    "id": "ant-ling",
    "name": "Ant Ling",
    "baseUrl": "https://api.ant-ling.com/v1",
    "api": "openai-completions",
    "models": 3,
    "modelIds": [
      "Ling-2.6-1T",
      "Ling-2.6-flash",
      "Ring-2.6-1T"
    ]
  },
  {
    "id": "anthropic",
    "name": "Anthropic",
    "baseUrl": "https://api.anthropic.com",
    "api": "anthropic-messages",
    "models": 14,
    "modelIds": [
      "claude-fable-5",
      "claude-fable-5-1",
      "claude-haiku-4-5",
      "claude-haiku-4-5-20251001",
      "claude-opus-4-5",
      "claude-opus-4-5-20251101",
      "claude-opus-4-6",
      "claude-opus-4-7",
      "claude-opus-4-8",
      "claude-opus-5",
      "claude-sonnet-4-5",
      "claude-sonnet-4-5-20250929",
      "claude-sonnet-4-6",
      "claude-sonnet-5"
    ]
  },
  {
    "id": "baseten",
    "name": "Baseten",
    "baseUrl": "https://inference.baseten.co/v1",
    "api": "openai-completions",
    "models": 20,
    "modelIds": [
      "deepseek-ai/DeepSeek-V4-Flash-0731",
      "deepseek-ai/DeepSeek-V4-Pro",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
      "moonshotai/Kimi-K2.5",
      "moonshotai/Kimi-K2.6",
      "moonshotai/Kimi-K2.7-Code",
      "moonshotai/Kimi-K3",
      "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
      "nvidia/Nemotron-120B-A12B",
      "openai/gpt-oss-120b",
      "thinkingmachines/inkling",
      "thinkingmachines/inkling-small",
      "zai-org/GLM-4.7",
      "zai-org/GLM-5",
      "zai-org/GLM-5.1",
      "zai-org/GLM-5.2",
      "zai-org/GLM-5.2-Fast",
      "zai-org/GLM-5.3",
      "zai-org/GLM-5.3-Fast",
      "zai-org/GLM-5.3-Flash"
    ]
  },
  {
    "id": "cerebras",
    "name": "Cerebras",
    "baseUrl": "https://api.cerebras.ai/v1",
    "api": "openai-completions",
    "models": 2,
    "modelIds": [
      "gemma-4-31b",
      "gpt-oss-120b"
    ]
  },
  {
    "id": "deepseek",
    "name": "DeepSeek",
    "baseUrl": "https://api.deepseek.com",
    "api": "openai-completions",
    "models": 3,
    "modelIds": [
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro"
    ]
  },
  {
    "id": "fireworks",
    "name": "Fireworks",
    "baseUrl": "https://api.fireworks.ai/inference",
    "api": "anthropic-messages",
    "models": 20,
    "modelIds": [
      "accounts/fireworks/models/deepseek-v4-flash-0731",
      "accounts/fireworks/models/deepseek-v4-flash-vision-exp",
      "accounts/fireworks/models/deepseek-v4-pro-0813",
      "accounts/fireworks/models/gpt-oss-120b",
      "accounts/fireworks/models/inkling",
      "accounts/fireworks/models/kimi-k2p6",
      "accounts/fireworks/models/kimi-k2p7-code",
      "accounts/fireworks/models/minimax-m3",
      "accounts/fireworks/models/muse-glimmer-30b",
      "accounts/fireworks/models/nemotron-3-ultra-nvfp4",
      "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b",
      "accounts/fireworks/models/qwen3p7-plus",
      "accounts/fireworks/models/qwen3p8-2p4t-a95b",
      "accounts/fireworks/models/qwen3p8-max",
      "accounts/fireworks/models/glm-5p2",
      "accounts/fireworks/models/glm-5p3",
      "accounts/fireworks/models/glm-5p3-flash",
      "accounts/fireworks/models/kimi-k3",
      "accounts/fireworks/routers/glm-5p2-fast",
      "accounts/fireworks/routers/kimi-k3-fast"
    ]
  },
  {
    "id": "github-copilot",
    "name": "GitHub Copilot",
    "baseUrl": "https://api.individual.githubcopilot.com",
    "api": "openai-responses",
    "models": 28,
    "modelIds": [
      "claude-fable-5",
      "claude-fable-5.1",
      "claude-haiku-4.5",
      "claude-opus-4.7",
      "claude-opus-4.8",
      "claude-opus-5",
      "claude-sonnet-4.6",
      "claude-sonnet-5",
      "gemini-3.5-flash",
      "gemini-3.6-flash",
      "gemini-3.7-flash",
      "gemini-3.8-flash",
      "gpt-6-astra",
      "kimi-k2.7-code",
      "kimi-k3",
      "gpt-5-mini",
      "gpt-5.3-codex",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5.5",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "grok-4.5",
      "grok-4.6",
      "mai-code-1-flash-picker",
      "mai-code-1.1-flash"
    ]
  },
  {
    "id": "google",
    "name": "Google",
    "baseUrl": "https://generativelanguage.googleapis.com/v1beta",
    "api": null,
    "models": 22,
    "modelIds": [
      "deep-research-max-preview-04-2026",
      "deep-research-preview-04-2026",
      "gemini-2.5-computer-use-preview-10-2025",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
      "gemini-2.5-pro",
      "gemini-3-flash-preview",
      "gemini-3.1-flash-lite",
      "gemini-3.1-flash-lite-image",
      "gemini-3.1-flash-lite-preview",
      "gemini-3.1-flash-live-preview",
      "gemini-3.1-pro-preview",
      "gemini-3.1-pro-preview-customtools",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.6-flash",
      "gemini-3.7-flash",
      "gemini-3.8-flash",
      "gemini-flash-latest",
      "gemini-flash-lite-latest",
      "gemma-4-26b-a4b-it",
      "gemma-4-31b-it"
    ]
  },
  {
    "id": "groq",
    "name": "Groq",
    "baseUrl": "https://api.groq.com/openai/v1",
    "api": "openai-completions",
    "models": 7,
    "modelIds": [
      "llama-3.1-8b-instant",
      "llama-3.3-70b-versatile",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "openai/gpt-oss-safeguard-20b",
      "qwen/qwen3.6-27b",
      "qwen/qwen3.8-27b"
    ]
  },
  {
    "id": "huggingface",
    "name": "Hugging Face",
    "baseUrl": "https://router.huggingface.co/v1",
    "api": "openai-completions",
    "models": 71,
    "modelIds": [
      "MiniMaxAI/MiniMax-M2",
      "MiniMaxAI/MiniMax-M2.1",
      "MiniMaxAI/MiniMax-M2.5",
      "MiniMaxAI/MiniMax-M2.7",
      "MiniMaxAI/MiniMax-M3",
      "Qwen/Qwen2.5-Coder-32B-Instruct",
      "Qwen/Qwen3-235B-A22B",
      "Qwen/Qwen3-235B-A22B-Instruct-2507",
      "Qwen/Qwen3-235B-A22B-Thinking-2507",
      "Qwen/Qwen3-30B-A3B",
      "Qwen/Qwen3-32B",
      "Qwen/Qwen3-Coder-30B-A3B-Instruct",
      "Qwen/Qwen3-Coder-480B-A35B-Instruct",
      "Qwen/Qwen3-Coder-Next",
      "Qwen/Qwen3-Next-80B-A3B-Instruct",
      "Qwen/Qwen3-Next-80B-A3B-Thinking",
      "Qwen/Qwen3-VL-235B-A22B-Instruct",
      "Qwen/Qwen3-VL-235B-A22B-Thinking",
      "Qwen/Qwen3.5-122B-A10B",
      "Qwen/Qwen3.5-27B",
      "Qwen/Qwen3.5-35B-A3B",
      "Qwen/Qwen3.5-397B-A17B",
      "Qwen/Qwen3.5-9B",
      "Qwen/Qwen3.6-27B",
      "Qwen/Qwen3.6-35B-A3B",
      "Qwen/Qwen3.8-2.4T-A95B",
      "Qwen/Qwen3.8-27B",
      "XiaomiMiMo/MiMo-V2-Flash",
      "XiaomiMiMo/MiMo-V2.5",
      "XiaomiMiMo/MiMo-V2.5-Pro",
      "deepseek-ai/DeepSeek-R1",
      "deepseek-ai/DeepSeek-R1-0528",
      "deepseek-ai/DeepSeek-V3",
      "deepseek-ai/DeepSeek-V3-0324",
      "deepseek-ai/DeepSeek-V3.1",
      "deepseek-ai/DeepSeek-V3.2",
      "deepseek-ai/DeepSeek-V4-Flash",
      "deepseek-ai/DeepSeek-V4-Flash-0731",
      "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
      "deepseek-ai/DeepSeek-V4-Pro",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
      "google/gemma-4-26B-A4B-it",
      "google/gemma-4-31B-it",
      "meta-llama/Llama-3.1-8B-Instruct",
      "meta-llama/Llama-3.3-70B-Instruct",
      "moonshotai/Kimi-K2-Instruct",
      "moonshotai/Kimi-K2-Instruct-0905",
      "moonshotai/Kimi-K2-Thinking",
      "moonshotai/Kimi-K2.5",
      "moonshotai/Kimi-K2.6",
      "moonshotai/Kimi-K2.7-Code",
      "moonshotai/Kimi-K3",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "stepfun-ai/Step-3.5-Flash",
      "stepfun-ai/Step-3.7-Flash",
      "tencent/Hy3",
      "thinkingmachines/Inkling",
      "thinkingmachines/Inkling-Small",
      "zai-org/GLM-4.5",
      "zai-org/GLM-4.5-Air",
      "zai-org/GLM-4.5V",
      "zai-org/GLM-4.6",
      "zai-org/GLM-4.6V-Flash",
      "zai-org/GLM-4.7",
      "zai-org/GLM-4.7-Flash",
      "zai-org/GLM-5",
      "zai-org/GLM-5.1",
      "zai-org/GLM-5.2",
      "zai-org/GLM-5.3",
      "zai-org/GLM-5.3-Flash"
    ]
  },
  {
    "id": "kimi-coding",
    "name": "Kimi For Coding",
    "baseUrl": "https://api.kimi.com/coding",
    "api": "anthropic-messages",
    "models": 4,
    "modelIds": [
      "k3",
      "k3-256k",
      "kimi-for-coding",
      "kimi-for-coding-highspeed"
    ]
  },
  {
    "id": "minimax",
    "name": "MiniMax",
    "baseUrl": "https://api.minimax.io/anthropic",
    "api": "anthropic-messages",
    "models": 3,
    "modelIds": [
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M3"
    ]
  },
  {
    "id": "minimax-cn",
    "name": "MiniMax CN",
    "baseUrl": "https://api.minimaxi.com/anthropic",
    "api": "anthropic-messages",
    "models": 3,
    "modelIds": [
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M3"
    ]
  },
  {
    "id": "mistral",
    "name": "Mistral",
    "baseUrl": "https://api.mistral.ai",
    "api": null,
    "models": 32,
    "modelIds": [
      "codestral-latest",
      "devstral-2512",
      "devstral-latest",
      "devstral-medium-2507",
      "devstral-medium-latest",
      "devstral-small-2505",
      "devstral-small-2507",
      "labs-devstral-small-2512",
      "magistral-medium-latest",
      "magistral-small",
      "ministral-3b-latest",
      "ministral-8b-latest",
      "mistral-large-2411",
      "mistral-large-2512",
      "mistral-large-latest",
      "mistral-medium-2505",
      "mistral-medium-2508",
      "mistral-medium-2604",
      "mistral-medium-3.5",
      "mistral-medium-latest",
      "mistral-nemo",
      "mistral-small-2506",
      "mistral-small-2603",
      "mistral-small-latest",
      "open-mistral-7b",
      "open-mistral-nemo",
      "open-mixtral-8x22b",
      "open-mixtral-8x7b",
      "pixtral-12b",
      "pixtral-large-latest",
      "voxtral-small-latest",
      "zai-glm-5-2"
    ]
  },
  {
    "id": "moonshotai",
    "name": "Moonshot AI",
    "baseUrl": "https://api.moonshot.ai/v1",
    "api": "openai-completions",
    "models": 10,
    "modelIds": [
      "kimi-k2-0711-preview",
      "kimi-k2-0905-preview",
      "kimi-k2-thinking",
      "kimi-k2-thinking-turbo",
      "kimi-k2-turbo-preview",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k3"
    ]
  },
  {
    "id": "moonshotai-cn",
    "name": "Moonshot AI CN",
    "baseUrl": "https://api.moonshot.cn/v1",
    "api": "openai-completions",
    "models": 10,
    "modelIds": [
      "kimi-k2-0711-preview",
      "kimi-k2-0905-preview",
      "kimi-k2-thinking",
      "kimi-k2-thinking-turbo",
      "kimi-k2-turbo-preview",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k3"
    ]
  },
  {
    "id": "nvidia",
    "name": "NVIDIA",
    "baseUrl": "https://integrate.api.nvidia.com/v1",
    "api": "openai-completions",
    "models": 20,
    "modelIds": [
      "deepseek-ai/deepseek-v4-flash-0731",
      "deepseek-ai/deepseek-v4-pro-0813",
      "google/gemma-3-12b-it",
      "google/gemma-3-4b-it",
      "meta/llama-3.2-11b-vision-instruct",
      "meta/llama-3.2-90b-vision-instruct",
      "meta/muse-glimmer-30b",
      "minimaxai/minimax-m3",
      "mistralai/mistral-7b-instruct-v0.3",
      "moonshotai/kimi-k2.6",
      "moonshotai/kimi-k3",
      "nvidia/cosmos-reason2-8b",
      "nvidia/llama-3.1-nemotron-70b-instruct",
      "nvidia/llama-3.1-nemotron-ultra-253b-v1",
      "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
      "nvidia/nemotron-3-super-120b-a12b",
      "nvidia/nemotron-3-ultra-550b-a55b",
      "nvidia/nemotron-3.5-lightning-30b-a3b",
      "openai/gpt-oss-20b",
      "poolside/laguna-xs-2.1"
    ]
  },
  {
    "id": "openai",
    "name": "OpenAI",
    "baseUrl": "https://api.openai.com/v1",
    "api": "openai-responses",
    "models": 39,
    "modelIds": [
      "gpt-4",
      "gpt-4-turbo",
      "gpt-4.1",
      "gpt-4.1-mini",
      "gpt-4.1-nano",
      "gpt-4o",
      "gpt-4o-2024-05-13",
      "gpt-4o-2024-08-06",
      "gpt-4o-2024-11-20",
      "gpt-4o-mini",
      "gpt-5",
      "gpt-5-chat-latest",
      "gpt-5-mini",
      "gpt-5-nano",
      "gpt-5-pro",
      "gpt-5.1",
      "gpt-5.2",
      "gpt-5.2-chat-latest",
      "gpt-5.2-pro",
      "gpt-5.3-chat-latest",
      "gpt-5.3-codex",
      "gpt-5.3-codex-spark",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5.4-pro",
      "gpt-5.5",
      "gpt-5.5-pro",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-6-astra",
      "gpt-realtime-2.1",
      "o1",
      "o1-pro",
      "o3",
      "o3-mini",
      "o3-pro",
      "o4-mini"
    ]
  },
  {
    "id": "openai-codex",
    "name": "OpenAI Codex",
    "baseUrl": "https://chatgpt.com/backend-api",
    "api": null,
    "models": 8,
    "modelIds": [
      "gpt-5.3-codex-spark",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.5",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-6-astra"
    ]
  },
  {
    "id": "openrouter",
    "name": "OpenRouter",
    "baseUrl": "https://openrouter.ai/api/v1",
    "api": "openai-completions",
    "models": 366,
    "modelIds": [
      "anthropic/claude-3-haiku",
      "anthropic/claude-fable-5",
      "anthropic/claude-fable-5.1",
      "anthropic/claude-haiku-4.5",
      "anthropic/claude-opus-4",
      "anthropic/claude-opus-4.1",
      "anthropic/claude-opus-4.5",
      "anthropic/claude-opus-4.6",
      "anthropic/claude-opus-4.7",
      "anthropic/claude-opus-4.8",
      "anthropic/claude-opus-5",
      "anthropic/claude-sonnet-4",
      "anthropic/claude-sonnet-4.5",
      "anthropic/claude-sonnet-4.6",
      "anthropic/claude-sonnet-5",
      "aion-labs/aion-2.0",
      "aion-labs/aion-3.0",
      "aion-labs/aion-3.0-mini",
      "amazon/nova-2-lite-v1",
      "amazon/nova-lite-v1",
      "amazon/nova-micro-v1",
      "amazon/nova-premier-v1",
      "amazon/nova-pro-v1",
      "anthropic/claude-fable-5.1:batch",
      "anthropic/claude-fable-5:batch",
      "anthropic/claude-haiku-4.5:batch",
      "anthropic/claude-opus-4.1:batch",
      "anthropic/claude-opus-4.5:batch",
      "anthropic/claude-opus-4.6:batch",
      "anthropic/claude-opus-4.7:batch",
      "anthropic/claude-opus-4.8:batch",
      "anthropic/claude-opus-5:batch",
      "anthropic/claude-sonnet-4.5:batch",
      "anthropic/claude-sonnet-4.6:batch",
      "anthropic/claude-sonnet-5:batch",
      "arcee-ai/trinity-large-thinking",
      "auto",
      "bytedance-seed/seed-1.6",
      "bytedance-seed/seed-1.6-flash",
      "bytedance-seed/seed-2-1-turbo",
      "bytedance-seed/seed-2.0-code",
      "bytedance-seed/seed-2.0-lite",
      "bytedance-seed/seed-2.0-mini",
      "cohere/command-r-08-2024",
      "cohere/command-r-plus-08-2024",
      "cohere/north-mini-code:free",
      "deepseek/deepseek-chat",
      "deepseek/deepseek-chat-v3-0324",
      "deepseek/deepseek-chat-v3.1",
      "deepseek/deepseek-r1",
      "deepseek/deepseek-r1-0528",
      "deepseek/deepseek-v3.1-terminus",
      "deepseek/deepseek-v3.2",
      "deepseek/deepseek-v3.2-exp",
      "deepseek/deepseek-v4-flash",
      "deepseek/deepseek-v4-flash-0731",
      "deepseek/deepseek-v4-flash-0731:batch",
      "deepseek/deepseek-v4-flash-vision-exp",
      "deepseek/deepseek-v4-pro",
      "deepseek/deepseek-v4-pro-0813",
      "deepseek/deepseek-v4-pro-0813:batch",
      "dots-studio/dots-3-note-preview:free",
      "google/gemini-2.5-flash",
      "google/gemini-2.5-flash-lite",
      "google/gemini-2.5-flash-lite:batch",
      "google/gemini-2.5-flash:batch",
      "google/gemini-2.5-pro",
      "google/gemini-2.5-pro-preview",
      "google/gemini-2.5-pro-preview-05-06",
      "google/gemini-2.5-pro:batch",
      "google/gemini-3-flash-preview",
      "google/gemini-3-flash-preview:batch",
      "google/gemini-3-pro-image",
      "google/gemini-3.1-flash-lite",
      "google/gemini-3.1-flash-lite-preview",
      "google/gemini-3.1-flash-lite:batch",
      "google/gemini-3.1-pro-preview",
      "google/gemini-3.1-pro-preview-customtools",
      "google/gemini-3.1-pro-preview:batch",
      "google/gemini-3.5-flash",
      "google/gemini-3.5-flash-lite",
      "google/gemini-3.5-flash-lite:batch",
      "google/gemini-3.5-flash:batch",
      "google/gemini-3.6-flash",
      "google/gemini-3.6-flash:batch",
      "google/gemini-3.7-flash",
      "google/gemini-3.7-flash:batch",
      "google/gemini-3.8-flash",
      "google/gemini-3.8-flash:batch",
      "google/gemma-3-12b-it",
      "google/gemma-3-27b-it",
      "google/gemma-4-26b-a4b-it",
      "google/gemma-4-26b-a4b-it:free",
      "google/gemma-4-31b-it",
      "google/gemma-4-31b-it:batch",
      "google/gemma-4-31b-it:free",
      "ibm-granite/granite-4.2-8b",
      "inception/mercury-2",
      "inception/mercury-2.5-preview",
      "inclusionai/ling-3.0-flash",
      "inclusionai/ling-3.0-flash-fin",
      "inclusionai/ling-3.0-flash-fin:free",
      "inclusionai/ling-3.0-flash-sante:free",
      "kwaipilot/kat-coder-pro-v2",
      "kwaipilot/kat-coder-pro-v2.5",
      "liquid/lfm-2.5-2.6b:free",
      "meituan/longcat-2.0",
      "meta-llama/llama-3.1-70b-instruct",
      "meta-llama/llama-3.1-8b-instruct",
      "meta-llama/llama-3.3-70b-instruct",
      "meta-llama/llama-4-maverick",
      "meta-llama/llama-4-scout",
      "meta/muse-glimmer-30b",
      "meta/muse-glimmer-30b:batch",
      "meta/muse-spark-1.1",
      "meta/muse-spark-1.2",
      "meta/muse-spark-1.2-contributor",
      "meta/muse-spark-1.3",
      "meta/muse-spark-1.3-contributor",
      "minimax/minimax-m1",
      "minimax/minimax-m2",
      "minimax/minimax-m2.1",
      "minimax/minimax-m2.5",
      "minimax/minimax-m2.7",
      "minimax/minimax-m2.7:free",
      "minimax/minimax-m3",
      "minimax/minimax-m3:batch",
      "minimax/minimax-m3:free",
      "mistralai/codestral-2508",
      "mistralai/devstral-2512",
      "mistralai/ministral-14b-2512",
      "mistralai/ministral-3b-2512",
      "mistralai/ministral-8b-2512",
      "mistralai/mistral-large",
      "mistralai/mistral-large-2407",
      "mistralai/mistral-large-2512",
      "mistralai/mistral-medium-3",
      "mistralai/mistral-medium-3-5",
      "mistralai/mistral-medium-3-5:batch",
      "mistralai/mistral-medium-3.1",
      "mistralai/mistral-nemo",
      "mistralai/mistral-saba",
      "mistralai/mistral-small-2603",
      "mistralai/mistral-small-3.2-24b-instruct",
      "mistralai/mixtral-8x22b-instruct",
      "mistralai/voxtral-small-24b-2507",
      "moonshotai/kimi-k2",
      "moonshotai/kimi-k2-0905",
      "moonshotai/kimi-k2-thinking",
      "moonshotai/kimi-k2.5",
      "moonshotai/kimi-k2.6",
      "moonshotai/kimi-k2.7-code",
      "moonshotai/kimi-k3",
      "moonshotai/kimi-k3:batch",
      "nex-agi/nex-n2-mini",
      "nex-agi/nex-n2-pro",
      "nvidia/nemotron-3-nano-30b-a3b",
      "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
      "nvidia/nemotron-3-super-120b-a12b",
      "nvidia/nemotron-3-super-120b-a12b:free",
      "nvidia/nemotron-3-ultra-550b-a55b",
      "nvidia/nemotron-3-ultra-550b-a55b:free",
      "nvidia/nemotron-3.5-lightning",
      "nvidia/nemotron-3.5-lightning:free",
      "openai/gpt-3.5-turbo",
      "openai/gpt-3.5-turbo-0613",
      "openai/gpt-3.5-turbo-16k",
      "openai/gpt-3.5-turbo:batch",
      "openai/gpt-4",
      "openai/gpt-4-turbo",
      "openai/gpt-4-turbo-preview",
      "openai/gpt-4-turbo:batch",
      "openai/gpt-4.1",
      "openai/gpt-4.1-mini",
      "openai/gpt-4.1-mini:batch",
      "openai/gpt-4.1-nano",
      "openai/gpt-4.1-nano:batch",
      "openai/gpt-4.1:batch",
      "openai/gpt-4o",
      "openai/gpt-4o-2024-05-13",
      "openai/gpt-4o-2024-08-06",
      "openai/gpt-4o-2024-11-20",
      "openai/gpt-4o-mini",
      "openai/gpt-4o-mini-2024-07-18",
      "openai/gpt-4o-mini:batch",
      "openai/gpt-4o:batch",
      "openai/gpt-5",
      "openai/gpt-5-mini",
      "openai/gpt-5-mini:batch",
      "openai/gpt-5-nano",
      "openai/gpt-5-nano:batch",
      "openai/gpt-5-pro",
      "openai/gpt-5-pro:batch",
      "openai/gpt-5.1",
      "openai/gpt-5.1-codex",
      "openai/gpt-5.1-codex-max",
      "openai/gpt-5.1-codex-mini",
      "openai/gpt-5.1:batch",
      "openai/gpt-5.2",
      "openai/gpt-5.2-chat",
      "openai/gpt-5.2-codex",
      "openai/gpt-5.2-pro",
      "openai/gpt-5.2-pro:batch",
      "openai/gpt-5.2:batch",
      "openai/gpt-5.3-codex",
      "openai/gpt-5.4",
      "openai/gpt-5.4-mini",
      "openai/gpt-5.4-mini:batch",
      "openai/gpt-5.4-nano",
      "openai/gpt-5.4-nano:batch",
      "openai/gpt-5.4-pro",
      "openai/gpt-5.4-pro:batch",
      "openai/gpt-5.4:batch",
      "openai/gpt-5.5",
      "openai/gpt-5.5-pro",
      "openai/gpt-5.5-pro:batch",
      "openai/gpt-5.5:batch",
      "openai/gpt-5.6-luna",
      "openai/gpt-5.6-luna-pro",
      "openai/gpt-5.6-luna-pro:batch",
      "openai/gpt-5.6-luna:batch",
      "openai/gpt-5.6-sol",
      "openai/gpt-5.6-sol-pro",
      "openai/gpt-5.6-sol-pro:batch",
      "openai/gpt-5.6-sol:batch",
      "openai/gpt-5.6-terra",
      "openai/gpt-5.6-terra-pro",
      "openai/gpt-5.6-terra-pro:batch",
      "openai/gpt-5.6-terra:batch",
      "openai/gpt-5:batch",
      "openai/gpt-6-astra",
      "openai/gpt-6-astra-pro",
      "openai/gpt-6-astra-pro:batch",
      "openai/gpt-6-astra:batch",
      "openai/gpt-audio",
      "openai/gpt-audio-mini",
      "openai/gpt-chat-latest",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-120b:batch",
      "openai/gpt-oss-20b",
      "openai/gpt-oss-safeguard-20b",
      "openai/o1",
      "openai/o3",
      "openai/o3-mini",
      "openai/o3-mini-high",
      "openai/o3-mini:batch",
      "openai/o3-pro",
      "openai/o3:batch",
      "openai/o4-mini",
      "openai/o4-mini-high",
      "openai/o4-mini:batch",
      "openrouter/auto",
      "openrouter/auto-beta",
      "openrouter/free",
      "openrouter/fusion",
      "poolside/laguna-s-2.1",
      "poolside/laguna-s-2.1:free",
      "poolside/laguna-xs-2.1",
      "poolside/laguna-xs-2.1:free",
      "qwen/qwen-2.5-72b-instruct",
      "qwen/qwen-2.5-7b-instruct",
      "qwen/qwen-plus",
      "qwen/qwen-plus-2025-07-28",
      "qwen/qwen3-14b",
      "qwen/qwen3-235b-a22b",
      "qwen/qwen3-235b-a22b-2507",
      "qwen/qwen3-235b-a22b-thinking-2507",
      "qwen/qwen3-30b-a3b",
      "qwen/qwen3-30b-a3b-instruct-2507",
      "qwen/qwen3-30b-a3b-thinking-2507",
      "qwen/qwen3-32b",
      "qwen/qwen3-8b",
      "qwen/qwen3-coder",
      "qwen/qwen3-coder-30b-a3b-instruct",
      "qwen/qwen3-coder-flash",
      "qwen/qwen3-coder-next",
      "qwen/qwen3-coder-plus",
      "qwen/qwen3-max",
      "qwen/qwen3-max-thinking",
      "qwen/qwen3-next-80b-a3b-instruct",
      "qwen/qwen3-next-80b-a3b-thinking",
      "qwen/qwen3-vl-235b-a22b-instruct",
      "qwen/qwen3-vl-235b-a22b-thinking",
      "qwen/qwen3-vl-30b-a3b-instruct",
      "qwen/qwen3-vl-30b-a3b-thinking",
      "qwen/qwen3-vl-32b-instruct",
      "qwen/qwen3-vl-8b-instruct",
      "qwen/qwen3-vl-8b-thinking",
      "qwen/qwen3.5-122b-a10b",
      "qwen/qwen3.5-27b",
      "qwen/qwen3.5-35b-a3b",
      "qwen/qwen3.5-397b-a17b",
      "qwen/qwen3.5-9b",
      "qwen/qwen3.5-9b:batch",
      "qwen/qwen3.5-flash-02-23",
      "qwen/qwen3.5-plus-02-15",
      "qwen/qwen3.5-plus-20260420",
      "qwen/qwen3.6-27b",
      "qwen/qwen3.6-35b-a3b",
      "qwen/qwen3.6-flash",
      "qwen/qwen3.6-max-preview",
      "qwen/qwen3.6-plus",
      "qwen/qwen3.7-flash",
      "qwen/qwen3.7-max",
      "qwen/qwen3.7-plus",
      "qwen/qwen3.8-2.4t-a95b",
      "qwen/qwen3.8-2.4t-a95b:batch",
      "qwen/qwen3.8-27b",
      "qwen/qwen3.8-flash",
      "qwen/qwen3.8-max-0902",
      "rekaai/reka-edge",
      "relace/relace-search",
      "sakana/fugu-ultra",
      "sakana/sakana-namazu",
      "sao10k/l3.1-euryale-70b",
      "stepfun/step-3.5-flash",
      "stepfun/step-3.7-flash",
      "tencent/hy3",
      "tencent/hy3-preview",
      "tencent/hy4-preview",
      "thedrummer/unslopnemo-12b",
      "thinkingmachines/inkling",
      "thinkingmachines/inkling-small",
      "thinkingmachines/inkling-small:batch",
      "thinkingmachines/inkling-small:free",
      "thinkingmachines/inkling:batch",
      "thinkingmachines/inkling:free",
      "upstage/solar-pro-3",
      "upstage/solar-pro4",
      "x-ai/grok-4.20",
      "x-ai/grok-4.3",
      "x-ai/grok-4.3:batch",
      "x-ai/grok-4.5",
      "x-ai/grok-4.6",
      "x-ai/grok-build-0.1",
      "xiaomi/mimo-v2.5",
      "xiaomi/mimo-v2.5-pro",
      "z-ai/glm-4.5",
      "z-ai/glm-4.5-air",
      "z-ai/glm-4.5v",
      "z-ai/glm-4.6",
      "z-ai/glm-4.6v",
      "z-ai/glm-4.7",
      "z-ai/glm-4.7-flash",
      "z-ai/glm-5",
      "z-ai/glm-5-turbo",
      "z-ai/glm-5.1",
      "z-ai/glm-5.2",
      "z-ai/glm-5.2:free",
      "z-ai/glm-5.3",
      "z-ai/glm-5.3-flash",
      "z-ai/glm-5.3-flash:batch",
      "z-ai/glm-5v-turbo",
      "~anthropic/claude-fable-latest",
      "~anthropic/claude-haiku-latest",
      "~anthropic/claude-opus-latest",
      "~anthropic/claude-sonnet-latest",
      "~deepseek/deepseek-v4-flash-latest",
      "~google/gemini-flash-latest",
      "~google/gemini-pro-latest",
      "~moonshotai/kimi-latest",
      "~openai/gpt-latest",
      "~openai/gpt-mini-latest",
      "~x-ai/grok-latest",
      "~z-ai/glm-flash-latest",
      "~z-ai/glm-latest"
    ]
  },
  {
    "id": "qwen-token-plan",
    "name": "Qwen Token Plan",
    "baseUrl": "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    "api": "openai-completions",
    "models": 18,
    "modelIds": [
      "MiniMax-M2.5",
      "deepseek-v3.2",
      "deepseek-v4-flash",
      "deepseek-v4-flash-0731",
      "deepseek-v4-pro",
      "deepseek-v4-pro-0813",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "qwen3.6-flash",
      "qwen3.6-plus",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.8-flash",
      "qwen3.8-max"
    ]
  },
  {
    "id": "qwen-token-plan-cn",
    "name": "Qwen Token Plan CN",
    "baseUrl": "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    "api": "openai-completions",
    "models": 18,
    "modelIds": [
      "MiniMax-M2.5",
      "deepseek-v3.2",
      "deepseek-v4-flash",
      "deepseek-v4-flash-0731",
      "deepseek-v4-pro",
      "deepseek-v4-pro-0813",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "qwen3.6-flash",
      "qwen3.6-plus",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.8-flash",
      "qwen3.8-max"
    ]
  },
  {
    "id": "qwen-token-plan-individual",
    "name": "Qwen Token Plan Individual",
    "baseUrl": "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    "api": "openai-completions",
    "models": 9,
    "modelIds": [
      "deepseek-v4-flash-0731",
      "deepseek-v4-pro",
      "deepseek-v4-pro-0813",
      "glm-5.2",
      "qwen3.6-flash",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.8-flash",
      "qwen3.8-max"
    ]
  },
  {
    "id": "together",
    "name": "Together",
    "baseUrl": "https://api.together.ai/v1",
    "api": "openai-completions",
    "models": 21,
    "modelIds": [
      "MiniMaxAI/MiniMax-M2.7",
      "MiniMaxAI/MiniMax-M3",
      "Qwen/Qwen2.5-7B-Instruct-Turbo",
      "Qwen/Qwen3.5-9B",
      "Qwen/Qwen3.6-Plus",
      "Qwen/Qwen3.7-Max",
      "deepseek-ai/DeepSeek-V4-Flash-0731",
      "deepseek-ai/DeepSeek-V4-Pro",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
      "google/gemma-4-31B-it",
      "meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "moonshotai/Kimi-K2.6",
      "moonshotai/Kimi-K2.7-Code",
      "moonshotai/Kimi-K3",
      "nvidia/nemotron-3-ultra-550b-a55b",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "thinkingmachines/Inkling",
      "zai-org/GLM-5.2",
      "zai-org/GLM-5.3",
      "zai-org/GLM-5.3-Flash"
    ]
  },
  {
    "id": "vercel-ai-gateway",
    "name": "Vercel AI Gateway",
    "baseUrl": "https://ai-gateway.vercel.sh",
    "api": "anthropic-messages",
    "models": 237,
    "modelIds": [
      "alibaba/qwen-3-14b",
      "alibaba/qwen-3-235b",
      "alibaba/qwen-3-30b",
      "alibaba/qwen-3-32b",
      "alibaba/qwen-3.6-max-preview",
      "alibaba/qwen3-235b-a22b-thinking",
      "alibaba/qwen3-coder",
      "alibaba/qwen3-coder-30b-a3b",
      "alibaba/qwen3-coder-next",
      "alibaba/qwen3-coder-plus",
      "alibaba/qwen3-max",
      "alibaba/qwen3-max-preview",
      "alibaba/qwen3-max-thinking",
      "alibaba/qwen3-next-80b-a3b-instruct",
      "alibaba/qwen3-next-80b-a3b-thinking",
      "alibaba/qwen3-vl-235b-a22b-instruct",
      "alibaba/qwen3-vl-instruct",
      "alibaba/qwen3-vl-thinking",
      "alibaba/qwen3.5-flash",
      "alibaba/qwen3.5-plus",
      "alibaba/qwen3.6-27b",
      "alibaba/qwen3.6-plus",
      "alibaba/qwen3.7-flash",
      "alibaba/qwen3.7-max",
      "alibaba/qwen3.7-plus",
      "alibaba/qwen3.8-2.4t-a95b",
      "alibaba/qwen3.8-27b",
      "alibaba/qwen3.8-flash",
      "alibaba/qwen3.8-flash-next",
      "alibaba/qwen3.8-max",
      "alibaba/qwen3.8-max-0902",
      "amazon/nova-2-lite",
      "amazon/nova-lite",
      "amazon/nova-micro",
      "amazon/nova-pro",
      "anthropic/claude-3-haiku",
      "anthropic/claude-fable-5",
      "anthropic/claude-fable-5.1",
      "anthropic/claude-haiku-4.5",
      "anthropic/claude-opus-4",
      "anthropic/claude-opus-4.5",
      "anthropic/claude-opus-4.6",
      "anthropic/claude-opus-4.7",
      "anthropic/claude-opus-4.8",
      "anthropic/claude-opus-4.8-fast",
      "anthropic/claude-opus-5",
      "anthropic/claude-opus-5-fast",
      "anthropic/claude-sonnet-4",
      "anthropic/claude-sonnet-4.5",
      "anthropic/claude-sonnet-4.6",
      "anthropic/claude-sonnet-5",
      "arcee-ai/trinity-large-thinking",
      "bytedance/seed-1.6",
      "bytedance/seed-1.8",
      "cohere/command-a",
      "deepseek/deepseek-r1",
      "deepseek/deepseek-v3.1",
      "deepseek/deepseek-v3.1-terminus",
      "deepseek/deepseek-v3.2",
      "deepseek/deepseek-v3.2-thinking",
      "deepseek/deepseek-v4-flash",
      "deepseek/deepseek-v4-flash-0731",
      "deepseek/deepseek-v4-flash-vision-exp",
      "deepseek/deepseek-v4-pro",
      "deepseek/deepseek-v4-pro-0813",
      "google/gemini-2.5-flash",
      "google/gemini-2.5-flash-lite",
      "google/gemini-2.5-pro",
      "google/gemini-3-flash",
      "google/gemini-3.1-flash-lite",
      "google/gemini-3.1-pro-preview",
      "google/gemini-3.5-flash",
      "google/gemini-3.5-flash-lite",
      "google/gemini-3.6-flash",
      "google/gemini-3.7-flash",
      "google/gemini-3.8-flash",
      "google/gemma-4-26b-a4b-it",
      "google/gemma-4-31b-it",
      "inception/mercury-2",
      "inception/mercury-coder-small",
      "inclusionai/ling-3.0-flash",
      "inclusionai/ling-3.0-flash-fin",
      "inclusionai/ling-3.0-flash-fin-free",
      "inclusionai/ling-3.0-flash-sante",
      "inclusionai/ling-3.0-flash-sante-free",
      "interfaze/interfaze-beta",
      "kwaipilot/kat-coder-air-v2.5",
      "kwaipilot/kat-coder-pro-v1",
      "kwaipilot/kat-coder-pro-v2",
      "kwaipilot/kat-coder-pro-v2.5",
      "meta/llama-3.1-70b",
      "meta/llama-3.1-8b",
      "meta/llama-3.3-70b",
      "meta/llama-4-maverick",
      "meta/llama-4-scout",
      "meta/muse-glimmer-30b",
      "meta/muse-spark-1.1",
      "meta/muse-spark-1.2",
      "meta/muse-spark-1.2-contributor",
      "meta/muse-spark-1.3",
      "meta/muse-spark-1.3-contributor",
      "minimax/minimax-m2",
      "minimax/minimax-m2.1",
      "minimax/minimax-m2.1-lightning",
      "minimax/minimax-m2.5",
      "minimax/minimax-m2.5-highspeed",
      "minimax/minimax-m2.7",
      "minimax/minimax-m2.7-free",
      "minimax/minimax-m2.7-highspeed",
      "minimax/minimax-m3",
      "minimax/minimax-m3-free",
      "mistral/codestral",
      "mistral/devstral-2",
      "mistral/devstral-small-2",
      "mistral/ministral-14b",
      "mistral/ministral-3b",
      "mistral/ministral-8b",
      "mistral/mistral-large-3",
      "mistral/mistral-medium",
      "mistral/mistral-medium-3.5",
      "mistral/mistral-nemo",
      "mistral/mistral-small",
      "mistral/pixtral-12b",
      "moonshotai/kimi-k2",
      "moonshotai/kimi-k2-thinking",
      "moonshotai/kimi-k2.5",
      "moonshotai/kimi-k2.6",
      "moonshotai/kimi-k2.7-code",
      "moonshotai/kimi-k2.7-code-highspeed",
      "moonshotai/kimi-k3",
      "moonshotai/kimi-k3-fast",
      "nvidia/nemotron-3-nano-30b-a3b",
      "nvidia/nemotron-3-super-120b-a12b",
      "nvidia/nemotron-3-ultra-550b-a55b",
      "nvidia/nemotron-3.5-lightning",
      "nvidia/nemotron-nano-12b-v2-vl",
      "nvidia/nemotron-nano-9b-v2",
      "openai/gpt-3.5-turbo",
      "openai/gpt-4-turbo",
      "openai/gpt-4.1",
      "openai/gpt-4.1-fast",
      "openai/gpt-4.1-mini",
      "openai/gpt-4.1-mini-fast",
      "openai/gpt-4.1-nano",
      "openai/gpt-4.1-nano-fast",
      "openai/gpt-4o",
      "openai/gpt-4o-fast",
      "openai/gpt-4o-mini",
      "openai/gpt-4o-mini-fast",
      "openai/gpt-5",
      "openai/gpt-5-codex",
      "openai/gpt-5-fast",
      "openai/gpt-5-mini",
      "openai/gpt-5-mini-fast",
      "openai/gpt-5-nano",
      "openai/gpt-5-pro",
      "openai/gpt-5.1-codex",
      "openai/gpt-5.1-codex-max",
      "openai/gpt-5.1-codex-mini",
      "openai/gpt-5.1-thinking",
      "openai/gpt-5.1-thinking-fast",
      "openai/gpt-5.2",
      "openai/gpt-5.2-codex",
      "openai/gpt-5.2-fast",
      "openai/gpt-5.2-pro",
      "openai/gpt-5.3-codex",
      "openai/gpt-5.3-codex-fast",
      "openai/gpt-5.4",
      "openai/gpt-5.4-fast",
      "openai/gpt-5.4-mini",
      "openai/gpt-5.4-mini-fast",
      "openai/gpt-5.4-nano",
      "openai/gpt-5.4-pro",
      "openai/gpt-5.5",
      "openai/gpt-5.5-fast",
      "openai/gpt-5.5-pro",
      "openai/gpt-5.6-luna",
      "openai/gpt-5.6-luna-fast",
      "openai/gpt-5.6-sol",
      "openai/gpt-5.6-sol-fast",
      "openai/gpt-5.6-terra",
      "openai/gpt-5.6-terra-fast",
      "openai/gpt-6-astra",
      "openai/gpt-6-astra-fast",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "openai/gpt-oss-safeguard-120b",
      "openai/gpt-oss-safeguard-20b",
      "openai/o1",
      "openai/o3",
      "openai/o3-fast",
      "openai/o3-mini",
      "openai/o3-pro",
      "openai/o4-mini",
      "openai/o4-mini-fast",
      "poolside/laguna-s-2.1",
      "poolside/laguna-s-2.1-free",
      "sakana/fugu-ultra",
      "sakana/namazu",
      "spacexai/grok-4.1-fast-non-reasoning",
      "spacexai/grok-4.1-fast-reasoning",
      "spacexai/grok-4.20-multi-agent",
      "spacexai/grok-4.20-multi-agent-beta",
      "spacexai/grok-4.20-non-reasoning",
      "spacexai/grok-4.20-non-reasoning-beta",
      "spacexai/grok-4.20-reasoning",
      "spacexai/grok-4.20-reasoning-beta",
      "spacexai/grok-4.3",
      "spacexai/grok-4.5",
      "spacexai/grok-4.6",
      "spacexai/grok-build-0.1",
      "stepfun/step-3.5-flash",
      "stepfun/step-3.7-flash",
      "tencent/hy3",
      "tencent/hy4-preview",
      "thinkingmachines/inkling",
      "thinkingmachines/inkling-small",
      "xiaomi/mimo-v2.5",
      "xiaomi/mimo-v2.5-pro",
      "xiaomi/mimo-v2.5-pro-ultraspeed",
      "zai/glm-4.5",
      "zai/glm-4.5-air",
      "zai/glm-4.5v",
      "zai/glm-4.6",
      "zai/glm-4.7",
      "zai/glm-4.7-flash",
      "zai/glm-4.7-flashx",
      "zai/glm-5",
      "zai/glm-5-turbo",
      "zai/glm-5.1",
      "zai/glm-5.2",
      "zai/glm-5.2-fast",
      "zai/glm-5.3",
      "zai/glm-5.3-fast",
      "zai/glm-5.3-flash",
      "zai/glm-5.3-promo-50",
      "zai/glm-5v-turbo"
    ]
  },
  {
    "id": "xai",
    "name": "xAI",
    "baseUrl": "https://api.x.ai/v1",
    "api": "openai-responses",
    "models": 3,
    "modelIds": [
      "grok-4.3",
      "grok-4.5",
      "grok-4.6"
    ]
  },
  {
    "id": "xiaomi",
    "name": "Xiaomi",
    "baseUrl": "https://api.xiaomimimo.com/v1",
    "api": "openai-completions",
    "models": 3,
    "modelIds": [
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2.5-pro-ultraspeed"
    ]
  },
  {
    "id": "xiaomi-token-plan-ams",
    "name": "Xiaomi Token Plan AMS",
    "baseUrl": "https://token-plan-ams.xiaomimimo.com/v1",
    "api": "openai-completions",
    "models": 2,
    "modelIds": [
      "mimo-v2.5",
      "mimo-v2.5-pro"
    ]
  },
  {
    "id": "xiaomi-token-plan-cn",
    "name": "Xiaomi Token Plan CN",
    "baseUrl": "https://token-plan-cn.xiaomimimo.com/v1",
    "api": "openai-completions",
    "models": 2,
    "modelIds": [
      "mimo-v2.5",
      "mimo-v2.5-pro"
    ]
  },
  {
    "id": "xiaomi-token-plan-sgp",
    "name": "Xiaomi Token Plan SGP",
    "baseUrl": "https://token-plan-sgp.xiaomimimo.com/v1",
    "api": "openai-completions",
    "models": 2,
    "modelIds": [
      "mimo-v2.5",
      "mimo-v2.5-pro"
    ]
  },
  {
    "id": "zai",
    "name": "Z.AI",
    "baseUrl": "https://api.z.ai/api/coding/paas/v4",
    "api": "openai-completions",
    "models": 7,
    "modelIds": [
      "glm-4.7",
      "glm-5-turbo",
      "glm-5.2",
      "glm-5.2-highspeed",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.3-highspeed"
    ]
  },
  {
    "id": "zai-coding-cn",
    "name": "Z.AI Coding CN",
    "baseUrl": "https://open.bigmodel.cn/api/coding/paas/v4",
    "api": "openai-completions",
    "models": 10,
    "modelIds": [
      "glm-4.6v",
      "glm-4.7",
      "glm-5-turbo",
      "glm-5.1",
      "glm-5.2",
      "glm-5.2-highspeed",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.3-highspeed",
      "glm-5v-turbo"
    ]
  }
];
