// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桥接的可用状态。界面按每种状态给不同去向，不显示「失败」了事。
 * 不写数目：这个集合会长，写进来的数字会在增删后说谎（这条已经栽过两次）。
 */
export type BridgeState = "app_unavailable" | "not_installed" | "incompatible" | "not_ready" | "connected";
