// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeState } from "./BridgeState";

export type BridgeStatus = { state: BridgeState, 
/**
 * 桥接自报的协议代次（只有 ping 成功才拿得到）
 */
protocol: number | null, 
/**
 * 本应用期望的代次，便于界面直接说出「期望几、拿到几」
 */
expectedProtocol: number, 
/**
 * 一次性安装步骤要粘进应用 Plugins 页的地址
 */
installUrl: string, };
