// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桥接的可用状态。界面按这四态给不同去向，不显示「失败」了事。
 */
export type BridgeState = "app_unavailable" | "not_installed" | "incompatible" | "connected";
