// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桌面档的一个 bundle（带 patch 层的插件包）
 */
export type BundleRow = { name: string, version: string | null, description: string | null, enabled: boolean, removable: boolean, readOnlyReason: string | null, };
