// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogEntry } from "./CatalogEntry";
import type { CatalogProvider } from "./CatalogProvider";

/**
 * 目录快照：缓存不是事实来源，fetched_at 供过期判断。
 * 与 models.dev 站点同构——providers 即服务商页行数，models 即 provider-agnostic
 * 模型页行数；两个计数都从数组长度得出，不额外存冗余字段。
 */
export type CatalogFile = { 
/**
 * unix 秒（IPC 走 JSON number）
 */
fetchedAt: number, providers: Array<CatalogProvider>, models: Array<CatalogEntry>, };
