// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * models.dev 投影条目：模型 id + 展示名 + 协议家族
 */
export type CatalogEntry = { id: string, name: string, 
/**
 * openai | anthropic（dsh pi-ai 无 gemini 原生协议，google 端点经 openai 兼容）
 */
family: string, };
