// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * models.dev 投影条目：模型 id + 展示名 + 协议家族 + 上下文窗口
 */
export type CatalogEntry = { id: string, name: string, 
/**
 * openai | anthropic（dsh pi-ai 无 gemini 原生协议，google 端点经 openai 兼容）
 */
family: string, 
/**
 * 目录标注的上下文窗口（token）；缺失为 null（UI 不显示缩写）
 */
context: number | null, };
