// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogEntry } from "./CatalogEntry";

/**
 * 目录快照：缓存不是事实来源，fetched_at 供过期判断
 */
export type CatalogFile = { 
/**
 * unix 秒（IPC 走 JSON number）
 */
fetchedAt: number, providerCount?: number, entries: Array<CatalogEntry>, };
