// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogEntry } from "./CatalogEntry";

/**
 * models.dev 服务商侧：该服务自己发布的模型，以及它声明的 wire 协议家族。
 * family 读 provider 自己的 SDK/端点声明，而不是模型 id 的归属者——否则 Claude
 * 模型会因为它同时被 OpenAI 兼容网关发布而丢失 anthropic 归属。
 */
export type CatalogProvider = { 
/**
 * models.dev provider key（服务商页路由键）
 */
id: string, name: string, 
/**
 * anthropic | openai（dsh pi-ai 无 gemini 原生协议，google 端点经 openai 兼容）
 */
family: string, 
/**
 * 该服务声明的端点；UI 用它把自定义 route 的服务匹配回目录服务商
 */
api?: string, 
/**
 * 该服务发布的模型；不做跨服务合并
 */
models: Array<CatalogEntry>, };
