// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * models.dev 投影条目：模型身份 + 核心容量/能力元数据。
 * 新增字段保持 optional，使旧快照仍可反序列化；新投影会完整填充这些字段。
 */
export type CatalogEntry = { id: string, name: string,
/**
 * openai | anthropic（dsh pi-ai 无 gemini 原生协议，google 端点经 openai 兼容）
 */
family: string,
/**
 * 目录标注的上下文窗口（token）；缺失为 null（UI 不显示缩写）
 */
context: number | null,
/**
 * 最大输出 token；旧快照/目录未发布时省略。
 */
maxTokens?: number,
/**
 * 已发布的输入模态（text/image/pdf/...）；未发布时省略。
 */
input?: Array<string>,
/**
 * models.dev 对 reasoning 的显式声明；未发布时省略而不是猜测。
 */
reasoning?: boolean,
/**
 * 规范化后的 reasoning 档位；none 归一为 off，按 dsh canonical order 排序。
 */
reasoningLevels?: Array<string>,
/**
 * 核心能力投影：text/vision/pdf/audio/video/tools/attachments/reasoning/json。
 */
capabilities?: Array<string>, };
