// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次管理操作的结果。上游把管理失败**折叠进返回值**而不是抛出，所以判断成败看
 * `application`，不是 HTTP 状态码也不是有没有 Err
 */
export type ChangeOutcome = { 
/**
 * applied / restart-required / overridden / failed / cancelled
 */
application: string, target: string, enabled: boolean | null, 
/**
 * 上游的错误码；failed 时才有
 */
errorCode: string | null, errorDiagnostic: string | null, 
/**
 * 需要用户显式放行的构建脚本；非空时这次安装没完成，要拿它原样再调一次
 */
pendingBuilds: Array<string>, warnings: Array<string>, };
