// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次插件变更被接受后的去向，两档同一套说法（失败不在这里：它是 Err）。web 档的启停
 * 写补丁层、重启 dsh web 后生效，正是 RestartRequired；内容没变的重复启停是 Unchanged。
 * desktop 档按桌面应用回报的结果给
 */
export type ChangeApplication = "applied" | "restart-required" | "overridden" | "cancelled" | "unchanged";
