// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitNoteInfo = { sha: string, 
/**
 * commit subject 是 GitHub API 的外部数据（原文即英文，无译文可言），
 * 不是可翻译句子：保持 String 原样透传，前端直接渲染
 */
message: string, date: string | null, };
