// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次变更被应用接受后的结果。失败不在这里：它转成 Err，原因是上游的诊断
 */
export type DesktopApplication = "applied" | "restart-required" | "overridden" | "cancelled";
