// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桌面档的一个已装插件：只列用户装的（可移除的）bundle——内置 bundle 不进已装列表，
 * 与 web 档只列 package.json 依赖对齐；内置 bundle 的启停留在桌面应用 tab
 */
export type DesktopInstalledPlugin = { name: string, version: string | null, enabled: boolean, 
/**
 * 桥接插件本身：显示，但不给移除与停用——停了它本应用就失去通往桌面档的通道
 */
managed: boolean, };
