// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleRow } from "./BundleRow";
import type { PluginRow } from "./PluginRow";

export type DesktopPlugins = { plugins: Array<PluginRow>, bundles: Array<BundleRow>, };
