// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新检查的结论。**三态而不是 Option**：None 无法区分「已是最新」与「查不出来」，
 * 而把后者说成前者是对用户撒谎——未安装、版本读不出、更新源不是通用静态服务都查不出来
 */
export type DesktopUpdate = { "kind": "available", version: string, } | { "kind": "upToDate" } | { "kind": "unknown" };
