// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桌面形态的外部状态。桥接态（插件是否已装、能否管理插件与配置）不在此结构里。
 */
export type DesktopStatus = { 
/**
 * 当前平台是否存在官方构建
 */
supported: boolean, installed: boolean, 
/**
 * 已安装版本；未安装为 None
 */
version: string | null, 
/**
 * 应用内置服务端口在监听（即应用正在运行）
 */
running: boolean, 
/**
 * 能否请求退出：仅 macOS 为真（见模块头）
 */
canQuit: boolean, };
