// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticDuplicate = { id: string, count: number, 
/**
 * 出现该 id 的层（去重，保序）
 */
layers: Array<string>, };
