// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发现页兼容性单条。requiresDsh 是 npm manifest 事实（磁盘缓存 24h），
 * compatible 按「当前宿主 dsh 版本」现算——结论不缓存，宿主升级后自然翻转
 * （B 方同语义：缓存事实、不缓存结论）
 */
export type DiscoveryCompat = { name: string, 
/**
 * 目标包最新版 manifest 声明的 dsh 最低版本（未声明为 None）
 */
requiresDsh: string | null, 
/**
 * None = 未声明（前端不隐藏，避免误判）；false = 确认不兼容；
 * true = 兼容
 */
compatible: boolean | null, };
