// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个 dist-tag 的版本行（latest/next 等）
 */
export type DshDistTag = { 
/**
 * dist-tag 名（latest / next / …）
 */
tag: string, 
/**
 * 该 tag 当前指向的版本
 */
version: string, 
/**
 * 本机已装版本即此版本
 */
isInstalled: boolean, 
/**
 * 高于 Launcher 验证栈（授权插件未验证）
 */
aboveSupported: boolean, 
/**
 * 过不了版本闸门（跨线或低于插件栈下限，装上本地与远程一起失效）
 */
incompatible: boolean, };
