// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DshDistTag } from "./DshDistTag";

/**
 * dsh 版本检测结果（设置页版本卡）：全部 dist-tag + 本机安装版本
 */
export type DshLatestInfo = { 
/**
 * registry 上所有 dist-tag（查询失败为空 vec）
 */
tags: Array<DshDistTag>, 
/**
 * 本机安装版本（未安装为 None）
 */
installedVersion: string | null, 
/**
 * Launcher 验证过的最低兼容版本（插件栈锁定）
 */
supportedVersion: string, 
/**
 * 查询失败原因（网络不通 / npm 不可用 / 输出无法解析）
 */
error: string | null, };
