// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteUrlAccess } from "./RemoteUrlAccess";
import type { StepEvent } from "./StepEvent";

export type DshStatus = { nodeAvailable: boolean, dshInstalled: boolean, dshVersion: string | null, supportedVersion: string, dshCompatible: boolean, 
/**
 * 实际版本高于 Launcher 验证过的锁定版本（仅兼容时才有意义）：
 * 授权插件栈在更新版下未验证，UI 据此提示风险而不阻断流程
 */
dshVersionAboveSupported: boolean, pluginsInstalled: boolean, dshRunning: boolean, tailscaleInstalled: boolean, tailscaleOnline: boolean, hostname: string | null, 
/**
 * 本机访问地址（dsh web 运行中即有，与授权插件无关）：优先 dsh 原生
 * 带 launch token 的地址（浏览器打开换取持久 cookie），解析不到回退裸地址
 */
localUrl: string | null, url: string | null, 
/**
 * 当前 Mac 用同一个 tailnet HTTPS 地址访问时的真实路径状态。
 * None 表示远程栈尚未形成 URL；ready / capability_denied /
 * proxy_interference / endpoint_failure 分别表示可用、远程 capability
 * 被拒、被本机代理截获、服务端链路失败。
 */
remoteUrlAccess: RemoteUrlAccess | null, magicDnsEnabled: boolean, serveConfigured: boolean, autostartEnabled: boolean, 
/**
 * 检测过程中的错误信息（无则 None）
 */
error: string | null, 
/**
 * 按本次检测推导的就绪时间轴（步骤序列 + 完成态）：前端未跑流程时的
 * 初始视图直接渲染它，不再自行从状态布尔重推导步骤编排
 */
readyTimeline: Array<StepEvent>, };
