// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportCandidate } from "./ImportCandidate";

/**
 * 按来源分组的扫描结果（固定来源顺序，缺失的来源为空组）
 */
export type ImportGroup = { source: string, entries: Array<ImportCandidate>, };
