// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportRunResult = { imported: number, skipped: number, failed: number, 
/**
 * 选中条目中来源为明文密钥的数量（提示用户补环境变量）
 */
literal: number, };
