// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个可导入的候选 provider（凭据明文永不进入本结构）
 */
export type ImportCandidate = { 
/**
 * `source:externalId`，run 的选择依据
 */
key: string, 
/**
 * 建议路由键（providers dict 的键）
 */
route: string, 
/**
 * 显示名
 */
name: string, baseURL: string | null, 
/**
 * wire 协议（openai-completions | openai-responses | anthropic-messages | null）
 */
api: string | null, 
/**
 * 环境变量引用名；仅 credential = "env" 时非空
 */
apiKeyEnv: string | null, 
/**
 * env = 环境变量引用 | literal = 来源持明文（值不导入）| none = 无凭据声明
 */
credential: string, models: Array<string>, };
