// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 安装回执：本次安装落进 profile 的 dependencies 键与 spec。
 * github: 重装等无法唯一确定落点的场景返回 None（安装本身仍成功）
 */
export type InstallReceipt = { name: string, spec: string, };
