// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallNotice } from "./InstallNotice";
import type { InstallReceipt } from "./InstallReceipt";

/**
 * 安装结果：成功带回执与护栏事实（notices）；被 pnpm 拦截构建脚本时转
 * 审批请求（被拦包名 + 待写文件路径）。审批是用户决策点：安装脚本以用户
 * 身份执行任意代码，launcher 不静默放行
 */
export type InstallOutcome = { "status": "installed", receipt: InstallReceipt | null, notices: Array<InstallNotice>, } | { "status": "needsApproval", packages: Array<string>, workspaceYaml: string, };
