// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledPlugin = { 
/**
 * npm 包名（profile package.json dependencies 键）
 */
name: string, 
/**
 * 安装 spec（file: tarball / npm:x@ver / github:owner/repo 等）
 */
spec: string, 
/**
 * Launcher 自管授权插件：不出移除按钮，由 Launcher 的修复/卸载流程管理
 */
managed: boolean, };
