// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 启动器配置，持久化到 ~/.dsh-pro-max/config.json
 */
export type LauncherConfig = { 
/**
 * 关闭窗口时是否最小化到系统托盘（false 则退出应用）
 */
minimize_to_tray_on_close: boolean, 
/**
 * 界面语言："system"（跟随系统）/ "en" / "zh-CN"
 */
language: string, 
/**
 * dsh 远程管理 capability 的域名部分（完整为 `{domain}/cap/dsh-admin`）。
 * 空 = 不注入 DSH_TAILSCALE_ADMIN_CAPABILITY，远程管理接口恒 403。
 */
dsh_admin_cap_domain: string, 
/**
 * dsh 远程普通使用 capability 的域名部分（完整为 `{domain}/cap/dsh`）。
 * 空 = 不注入 DSH_TAILSCALE_USE_CAPABILITY；
 * 普通远程访问仍需身份 allowlist 与 tailnet TCP 443 grant。
 */
dsh_use_cap_domain: string, 
/**
 * 额外允许访问 dsh 的 Tailscale 登录名（逗号分隔）；本机当前用户始终自动包含。
 */
dsh_extra_allowed_logins: string, 
/**
 * 插件市场目录源（企业内网镜像）。空 = 内置官方源；
 * 非空必须是 https:// 或 http:// 地址，且返回同一 JSON 契约（schemaVersion 1）
 */
market_catalog_url: string, };
