// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDuplicate } from "./DiagnosticDuplicate";

/**
 * 诊断快照（dump-config 一次运行的组合事实）。结构化载荷：语言由前端
 * 词典组装，不随 Rust 字符串漂移
 */
export type MarketDiagnostics = { entries: number, 
/**
 * disabled: true 的条目数（启停覆盖行生效中）
 */
disabled: number, 
/**
 * 重复 loader 入口 id（下次启动必挂的组合病；disabled 条目不豁免——
 * loader 拒绝的是重复 id 本身，B 方同语义）
 */
duplicates: Array<DiagnosticDuplicate>, 
/**
 * 孤儿 patch 行引用的入口 id（dsh 启动时警告并跳过）
 */
orphans: Array<string>, };
