// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketPlugin = { 
/**
 * `owner/name`（owner 缺失时从 repo url 派生）：展示与排序键
 */
fullName: string, name: string, 
/**
 * 多语言描述原样透传（如 {"en": "...", "zh": "..."}），前端按界面语言取
 */
description: Record<string, string>, url: string, 
/**
 * null = 目录暂无数据（新收录或仓库 404），不静默当 0
 */
stars: number | null, 
/**
 * 分类 id（显示名经目录顶层的 categories 表本地化）
 */
category: string | null, 
/**
 * 目录 `install` 命令串中解析出的安装标识；None = 无一键安装候选，
 * 前端显示 Manual install only
 */
installSpecifier: string | null, 
/**
 * 目录侧弃用标记原样透传
 */
deprecated: boolean, 
/**
 * 弃用时目录建议的替代插件名
 */
replacement: string | null, };
