// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 安装输出行事件（`market-install-log`）：specifier 锚定前端卡片（安装全局
 * 单飞，带上是防御错位），line 为 dsh/pnpm 子进程的展示行
 */
export type MarketInstallLogEvent = { specifier: string, line: string, };
