// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketPlugin } from "./MarketPlugin";

export type MarketCatalog = { 
/**
 * 目录生成日期（目录原生 `updated`，如 "2026-08-31"）
 */
updated: string | null, 
/**
 * 分类 id → {语言 → 显示名}，目录原生表原样透传（前端按界面语言取）
 */
categories: Record<string, Record<string, string>>, total: number, plugins: Array<MarketPlugin>, 
/**
 * 数据来自本地快照（首屏直读或断网降级）；UI 在刷新结束后如实标注
 */
fromSnapshot: boolean, };
