// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * 消息参数值：普通文本，或一条可继续本地化的嵌套消息（如「回滚原因」本身
 * 也是一条诊断）。嵌套时前端递归解析，内层也走词典，不会被提前压成英文
 */
export type MessageArg = string | Message;
