// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageArg } from "./MessageArg";

/**
 * 过 IPC 的用户可见消息。
 *
 * key 是本地化前的稳定英文原文；带 `{{name}}` 占位符时由 args 插值。
 * 技术性文案（路径、原始 stderr、无法模板化的整句）没有占位符，整串当 key
 * 传递、args 为空，与「原样显示英文」的旧行为逐字一致
 */
export type Message = { key: string, args: { [key in string]?: MessageArg }, };
