// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelCredentialInfo = { 
/**
 * 当前按 DSH precedence 解析是否能得到非空值。
 */
configured: boolean, 
/**
 * env | file | project-env | user-env；未配置时为 null。
 */
source: string | null, 
/**
 * inherited process env 是只读，其余层可由 managed file 覆盖。
 */
writable: boolean, };
