// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEfforts } from "./ReasoningEfforts";

export type ModelEntry = { 
/**
 * 模型 id（请求身份），非空
 */
id: string, 
/**
 * 显示名；缺省回落目录名或 id
 */
name: string | null, 
/**
 * 上下文窗口（token）；缺省继承目录
 */
contextWindow: number | null, 
/**
 * 最大输出（token）；缺省继承目录
 */
maxTokens: number | null, 
/**
 * 输入模态原样保留（text/image/...）；UI 以三态开关投影，缺省=继承目录
 */
input: Array<string> | null, 
/**
 * 推理档声明原样；缺省=继承目录（手写模型视为不支持推理）
 */
reasoningEfforts: ReasoningEfforts | null, 
/**
 * 条目内非管理键（compat 等），原样透传
 */
extra: import("./serde_json/JsonValue").JsonValue, };
