// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

export type ModelConfig = { defaultProvider: string | null, defaultModel: string | null, 
/**
 * 思考等级：off | minimal | low | medium | high | xhigh | max
 */
defaultReasoningEffort: string | null, providers: Array<ProviderConfig>, };
