// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 桌面档的一个插件行
 */
export type PluginRow = { 
/**
 * 翻转启用状态要回传的标识（上游的品牌类型，必须原样带回）
 */
entryId: string, moduleName: string, enabled: boolean, 
/**
 * 有值才可经 profile 补丁翻转；否则 read_only_reason 说明为什么不行
 */
patchId: string | null, readOnlyReason: string | null, };
