// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 插件更新检测的单包结果。检测范围 = npm 形态安装的非受管插件：实际版本
 * 优先取磁盘事实（node_modules 内 package.json 的 version，范围 spec
 * `^x.y.z` 就靠它参与检测），磁盘不可得回退 spec 精确版本；协议形态
 * （github:/file: 等）来源不是 registry，恒不检（不猜）
 */
export type PluginUpdateInfo = { name: string, 
/**
 * 落盘 spec 原文（file:/github: 等形态如实展示）
 */
spec: string, managed: boolean, 
/**
 * 实际安装版本：磁盘事实（node_modules/<name>/package.json）优先，
 * spec 精确版本次之；协议形态与两者均不可得时为 None
 */
installedVersion: string | null, 
/**
 * registry latest；该包查询失败为 None
 */
latestVersion: string | null, 
/**
 * latest 是否落在 pnpm minimumReleaseAge 保护窗口内（pnpm 11 内置默认
 * 24h）：窗口内 @latest 会被静默解析回旧版、退出码仍为 0（假成功），
 * 前端据此先弹供应链确认框，用户知情确认后才钉版本重装
 */
latestInReleaseAgeWindow: boolean, 
/**
 * latestVersion 的发布时间（RFC3339，来自完整 packument 的 time 字段，
 * 仅对确有更新的包多付一次 HTTP 取得）。供应链确认框据此展示"发布
 * 多久了"——新鲜度是用户"等窗口过期还是现在就装"决策的核心事实；
 * packument 不可得（网络失败等）为 None，前端回退"刚发布"模糊文案
 */
latestPublishTime: string | null, 
/**
 * 目标包最新版 manifest 声明的 dsh 最低版本（包 manifest 的
 * `dsh.engines.dsh`，回退顶层 `engines.dsh`；未声明为 None）
 */
requiresDsh: string | null, 
/**
 * 宿主 dsh 是否满足 requiresDsh。未声明为 None；声明后宿主版本不可得、
 * 声明形态不支持或任一侧解析失败一律 false——声明了的最低版本不能
 * 装作满足（fail closed）
 */
compatible: boolean | null, updateAvailable: boolean, };
