// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitNoteInfo } from "./CommitNoteInfo";
import type { ReleaseNotesInfo } from "./ReleaseNotesInfo";

/**
 * 更新说明载荷：release 为探针未覆盖时的 None（小插件的常态，前端如实
 * 显示"暂无说明"而非报错）
 */
export type PluginReleaseNotes = { release: ReleaseNotesInfo | null, commits: Array<CommitNoteInfo>, };
