// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 插件更新检测的单包结果。检测范围 = npm 形态安装的非受管插件：协议形态
 * （github:/file: 等）来源不是 registry、范围 spec 无具体版本可比，均如实
 * 返回 None（不猜）；受管插件由 Launcher 的修复流程管理，不参与
 */
export type PluginUpdateInfo = { name: string, 
/**
 * 落盘 spec 原文（file:/github: 等形态如实展示）
 */
spec: string, managed: boolean, 
/**
 * 从 spec 解析出的具体当前版本；范围/协议形态为 None
 */
installedVersion: string | null, 
/**
 * registry latest；该包查询失败为 None
 */
latestVersion: string | null, updateAvailable: boolean, };
