// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelEntry } from "./ModelEntry";

export type ProviderConfig = { 
/**
 * 提供商路由键（providers dict 的键，如 spero-ai），非空
 */
route: string, 
/**
 * 显示名；缺省回落路由键
 */
displayName: string | null, baseURL: string | null, 
/**
 * wire 协议：openai-completions | openai-responses | anthropic-messages；
 * 缺省时目录路由继承目录协议
 */
api: string | null, 
/**
 * 凭据引用（环境变量名），密钥永不落盘
 */
apiKeyEnv: string | null, 
/**
 * 本路由的模型条目；空 = 不写 models 键（继承内置目录）
 */
models: Array<ModelEntry>, 
/**
 * 请求头（凭据类保留头由 UI 拒收；dsh Harness 归因头优先）
 */
headers: { [key in string]?: string } | null, 
/**
 * 请求超时（毫秒）
 */
timeoutMs: number | null, 
/**
 * 本路由默认推理档：off..max
 */
reasoning: string | null, 
/**
 * 本路由的非管理键（compat、重试策略等高级字段），原样透传
 */
extra: import("./serde_json/JsonValue").JsonValue, };
