// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderConfig = { 
/**
 * 提供商路由键（providers dict 的键，如 spero-ai），非空
 */
route: string, 
/**
 * 显示名；缺省回落路由键
 */
displayName: string | null, baseURL: string | null, 
/**
 * wire 协议：openai-completions | openai-responses | anthropic-messages
 */
api: string | null, 
/**
 * 凭据引用（环境变量名），密钥永不落盘
 */
apiKeyEnv: string | null, 
/**
 * 模型 id 列表（models[].id）
 */
models: Array<string>, 
/**
 * 本路由的非管理键（高级字段），原样透传
 */
extra: import("./serde_json/JsonValue").JsonValue, };
