// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * dsh reasoningEfforts 原样形态：false = 手写声明不支持推理（UI 不改写，
 * 原样保留）；map = 档位 → wire 拼写（null = 支持但不发参，仅 off 档合法）
 */
export type ReasoningEfforts = boolean | { [key in string]?: string | null };
