// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReleaseNotesInfo = { tag: string | null, name: string | null, publishedAt: string | null, url: string | null, 
/**
 * GitHub release 正文原样透传（markdown，前端滚动展示）
 */
body: string, };
