// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * 时间轴节点事件（dsh-step），由 dsh_setup / dsh_start_web 逐步发出。
 * state 全集含 "pending"——派生时间轴（ready_timeline）与前端骨架用它，
 * 事件流自身只发 running/done/failed/skipped
 */
export type StepEvent = { index: number, id: string, 
/**
 * running | done | failed | skipped | pending（pending 只见于派生时间轴/前端骨架）
 */
state: "running" | "done" | "failed" | "skipped" | "pending", 
/**
 * 明细行：首行是基线文案，其后是追加的披露行（每行独立本地化，
 * 前端逐行渲染；空列表即无明细）
 */
detail: Array<Message>, 
/**
 * 问题描述（失败节点展示）
 */
problem: Message | null, 
/**
 * 解决方案（失败节点展示）
 */
solution: Message | null, 
/**
 * 可一键禁用重试的第三方插件包名（仅启动失败的插件归因节点携带；
 * 受管授权插件为 None——其恢复路径是 Repair dsh stack）
 */
actionPlugin: string | null, 
/**
 * 步骤标题的 i18n key（"step.<id>"）：骨架/派生时间轴节点携带，
 * 前端零映射渲染；事件流节点为 None（标题已由骨架就位）
 */
titleKey: string | null, };
