// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export type UpdateInfo = { currentVersion: string, availableVersion: string | null, hasUpdate: boolean, releaseNotes: string | null, message: Message | null, };
