//! 开机自启：launchd(macOS) / 启动文件夹 .vbs(Windows) / systemd --user(Linux) 三平台实现。

use super::{ADMIN_CAP_ENV, TAILSCALE_LOGIN_ENV, USE_CAP_ENV, WEB_PORT};
// AUTOSTART_PREFIX 仅 macOS launchd 分支使用（常量本身 cfg(macos)）
#[cfg(target_os = "macos")]
use super::AUTOSTART_PREFIX;
use super::auth::{AuthConfig, resolve_auth_config, resolve_fqdn, resolve_tailscale_login};
use super::components::{dsh_dir, dsh_version, dsh_version_is_compatible, install_auth_plugins, install_supported_dsh, resolve_dsh_bin, resolve_node_bin, tailscale_path};
use super::process::{kill_by_pattern};
use std::fs;
use std::path::{Path};
use std::process::Command;


use crate::config;
use crate::i18n::{tr, trf};

// ============ 开机自启（launchd / 启动文件夹 / systemd --user） ============

/// sh 单引号转义（生成的启动脚本内嵌绝对路径）
pub(crate) fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// 端口占用守卫脚本（node 一段式）：端口已被监听 → exit 0（自启服务不重复启动）
pub(crate) fn port_guard_js(port: u16) -> String {
    format!(
        "const net=require('net');const s=net.connect({port},'127.0.0.1');s.on('connect',()=>process.exit(0));s.on('error',()=>process.exit(1));setTimeout(()=>process.exit(1),1000).unref();",
        port = port
    )
}

/// 生成 dsh web 启动脚本（自启用）：带端口守卫、loopback 绑定、
/// Tailscale 授权身份、按配置解析的 use/admin App Capability 与 --trusted-host。
#[cfg_attr(windows, allow(dead_code))]
pub(crate) fn render_start_web(node: &str, dsh: &str, host: &str, login: &str, auth: &AuthConfig) -> String {
    let trusted = if host.is_empty() {
        String::new()
    } else {
        format!(" --trusted-host {}", sh_quote(host))
    };
    // dsh 是 npm shim（#!/usr/bin/env node）：launchd/systemd 的裸 PATH 下
    // env 找不到 node，shim 以 127 秒退（实机踩坑：开机自启从未真正拉起
    // dsh web）。把 node 所在目录补进 PATH，shim 才能解析到解释器
    let node_dir = Path::new(node)
        .parent()
        .map(|p| p.display().to_string())
        .unwrap_or_default();
    let use_cap_line = auth
        .use_capability
        .as_deref()
        .map(|cap| format!("export {USE_CAP_ENV}={}\n", sh_quote(cap)))
        .unwrap_or_default();
    let admin_cap_line = auth
        .admin_capability
        .as_deref()
        .map(|cap| format!("export {ADMIN_CAP_ENV}={}\n", sh_quote(cap)))
        .unwrap_or_default();
    format!(
        "#!/bin/sh\n# generated by DSH Pro Max; do not edit\nif {node} -e {guard}; then exit 0; fi\nexport PATH={node_dir}:$PATH\nexport {login_env}={login}\n{use_cap_line}{admin_cap_line}exec {dsh} --profile web --host 127.0.0.1 --port {port} --no-open{trusted}\n",
        node = sh_quote(node),
        guard = sh_quote(&port_guard_js(WEB_PORT)),
        node_dir = sh_quote(&node_dir),
        login_env = TAILSCALE_LOGIN_ENV,
        login = sh_quote(&auth.allowed_logins(login)),
        use_cap_line = use_cap_line,
        admin_cap_line = admin_cap_line,
        dsh = sh_quote(dsh),
        port = WEB_PORT,
        trusted = trusted,
    )
}

/// XML 转义（plist 内容，仅 macOS launchd 使用）
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub(crate) fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

pub(crate) fn autostart_enabled() -> bool {
    #[cfg(target_os = "macos")]
    {
        config::home_dir()
            .map(|h| {
                h.join("Library/LaunchAgents")
                    .join(format!("{}.web.plist", AUTOSTART_PREFIX))
                    .exists()
            })
            .unwrap_or(false)
    }
    #[cfg(windows)]
    {
        // 启动文件夹里的 .vbs 是否存在
        windows_startup_dir()
            .map(|d| d.join("dsh-remote-autostart.vbs").exists())
            .unwrap_or(false)
    }
    #[cfg(target_os = "linux")]
    {
        // systemd unit 与 XDG autostart .desktop 任一存在即视为已开启
        config::home_dir()
            .map(|h| {
                h.join(".config/systemd/user")
                    .join("dsh-remote-web.service")
                    .exists()
                    || h.join(".config/autostart")
                        .join("dsh-remote-web.desktop")
                        .exists()
            })
            .unwrap_or(false)
    }
}

#[tauri::command]
pub fn dsh_set_autostart(app: tauri::AppHandle, enabled: bool) -> Result<(), String> {
    if enabled {
        if !dsh_version_is_compatible(dsh_version().as_deref()) {
            install_supported_dsh()?;
        }
        install_auth_plugins(&app)?;
    }
    autostart_impl(enabled).map_err(|e| {
        log::error!("[dsh 自启] {} 失败: {}", if enabled { "开启" } else { "关闭" }, e);
        e
    })
}

#[cfg(target_os = "macos")]
pub(crate) fn autostart_impl(enabled: bool) -> Result<(), String> {
    let home = config::home_dir()?;
    let agents_dir = home.join("Library/LaunchAgents");
    let dsh = dsh_dir()?;
    let web_plist = agents_dir.join(format!("{}.web.plist", AUTOSTART_PREFIX));
    let legacy_proxy_plist = agents_dir.join(format!("{}.proxy.plist", AUTOSTART_PREFIX));
    let web_script = dsh.join("start-web.sh");
    let legacy_proxy_script = dsh.join("start-proxy.sh");

    let unload = |label: &str, plist: &Path| {
        let _ = Command::new("launchctl")
            .args(["unload", "-w"])
            .arg(plist)
            .output();
        let _ = Command::new("launchctl").arg("remove").arg(label).output();
    };
    unload(&format!("{}.proxy", AUTOSTART_PREFIX), &legacy_proxy_plist);
    let _ = fs::remove_file(&legacy_proxy_plist);
    let _ = fs::remove_file(&legacy_proxy_script);
    kill_by_pattern("loopback-proxy.js");

    if enabled {
        let node = resolve_node_bin()?;
        let dsh_bin = resolve_dsh_bin()?;
        let ts = tailscale_path().ok_or_else(|| tr("Tailscale is not installed"))?;
        let login = resolve_tailscale_login(&ts)?;
        let fqdn = resolve_fqdn().unwrap_or_default();
        let auth = resolve_auth_config()?;
        fs::create_dir_all(&agents_dir).map_err(|error| {
            log::error!("[dsh 自启(mac)] 创建 LaunchAgents 目录失败: {}", error);
            trf(
                "Failed to create directory: {error}",
                &[("error", error.to_string())],
            )
        })?;
        fs::write(
            &web_script,
            render_start_web(&node, &dsh_bin.display().to_string(), &fqdn, &login, &auth),
        )
        .map_err(|error| {
            log::error!("[dsh 自启(mac)] 写启动脚本失败: {}", error);
            trf(
                "Failed to write {path}: {error}",
                &[
                    ("path", web_script.display().to_string()),
                    ("error", error.to_string()),
                ],
            )
        })?;

        let web_label = format!("{}.web", AUTOSTART_PREFIX);
        let plist = format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>{script}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{home}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>{log}</string>
    <key>StandardErrorPath</key>
    <string>{log}</string>
</dict>
</plist>
"#,
            label = web_label,
            script = xml_escape(&web_script.display().to_string()),
            home = xml_escape(&home.display().to_string()),
            log = xml_escape(&dsh.join("launchd-web.log").display().to_string()),
        );
        fs::write(&web_plist, plist).map_err(|error| {
            log::error!("[dsh 自启(mac)] 写 plist 失败: {}", error);
            trf(
                "Failed to write {path}: {error}",
                &[
                    ("path", web_plist.display().to_string()),
                    ("error", error.to_string()),
                ],
            )
        })?;
        unload(&format!("{}.web", AUTOSTART_PREFIX), &web_plist);
        Command::new("launchctl")
            .args(["load", "-w"])
            .arg(&web_plist)
            .output()
            .map_err(|error| {
                log::error!("[dsh 自启(mac)] 注册 launchd agent 失败: {}", error);
                trf(
                    "Cannot register launchd agent: {error}",
                    &[("error", error.to_string())],
                )
            })?;
    } else {
        unload(&format!("{}.web", AUTOSTART_PREFIX), &web_plist);
        let _ = fs::remove_file(&web_plist);
        let _ = fs::remove_file(&web_script);
    }
    Ok(())
}
#[cfg(target_os = "windows")]
pub(crate) fn windows_startup_dir() -> Option<PathBuf> {
    let appdata = std::env::var("APPDATA").ok()?;
    Some(
        PathBuf::from(appdata)
            .join("Microsoft")
            .join("Windows")
            .join("Start Menu")
            .join("Programs")
            .join("Startup"),
    )
}

#[cfg(target_os = "windows")]
pub(crate) fn autostart_impl(enabled: bool) -> Result<(), String> {
    let dsh = dsh_dir()?;
    fs::create_dir_all(&dsh).map_err(|error| {
        log::error!("[dsh 自启(win)] 创建 ~/.dsh 目录失败: {}", error);
        trf(
            "Failed to create directory: {error}",
            &[("error", error.to_string())],
        )
    })?;
    let web_cmd = dsh.join("start-web.cmd");
    let legacy_proxy_cmd = dsh.join("start-proxy.cmd");
    let startup = windows_startup_dir()
        .ok_or_else(|| {
            let err = tr("Cannot locate the Windows Startup folder (APPDATA is missing)");
            log::error!("[dsh 自启(win)] {}", err);
            err
        })?;
    let vbs = startup.join("dsh-remote-autostart.vbs");

    let _ = fs::remove_file(&legacy_proxy_cmd);
    kill_by_pattern("loopback-proxy.js");

    if enabled {
        let node = resolve_node_bin()?;
        let dsh_bin = resolve_dsh_bin()?;
        let ts = tailscale_path().ok_or_else(|| tr("Tailscale is not installed"))?;
        let login = resolve_tailscale_login(&ts)?;
        let fqdn = resolve_fqdn().unwrap_or_default();
        let auth = resolve_auth_config()?;
        let trusted = if fqdn.is_empty() {
            String::new()
        } else {
            format!(" --trusted-host {}", fqdn)
        };
        let node_dir = Path::new(&node)
            .parent()
            .map(|path| path.display().to_string())
            .unwrap_or_default();
        let use_cap_line = auth
            .use_capability
            .as_deref()
            .map(|cap| format!("set \"{USE_CAP_ENV}={cap}\"\r\n"))
            .unwrap_or_default();
        let admin_cap_line = auth
            .admin_capability
            .as_deref()
            .map(|cap| format!("set \"{ADMIN_CAP_ENV}={cap}\"\r\n"))
            .unwrap_or_default();
        let web = format!(
            "@echo off\r\nrem generated by DSH Pro Max; do not edit\r\nset \"PATH={node_dir};%PATH%\"\r\n\"{node}\" -e \"{guard}\" >nul 2>&1\r\nif %errorlevel%==0 exit /b 0\r\nset \"{login_env}={login}\"\r\n{use_cap_line}{admin_cap_line}call \"{dsh}\" --profile web --host 127.0.0.1 --port {port}{trusted}\r\n",
            node_dir = node_dir,
            node = node,
            guard = port_guard_js(WEB_PORT),
            login_env = TAILSCALE_LOGIN_ENV,
            login = auth.allowed_logins(&login),
            use_cap_line = use_cap_line,
            admin_cap_line = admin_cap_line,
            dsh = dsh_bin.display(),
            port = WEB_PORT,
            trusted = trusted,
        );
        fs::write(&web_cmd, web).map_err(|error| {
            log::error!("[dsh 自启(win)] 写 start-web.cmd 失败: {}", error);
            trf(
                "Failed to write {path}: {error}",
                &[
                    ("path", web_cmd.display().to_string()),
                    ("error", error.to_string()),
                ],
            )
        })?;
        let vbs_body = format!(
            "' generated by DSH Pro Max; do not edit\r\nSet sh = CreateObject(\"WScript.Shell\")\r\nsh.Run \"\"\"{web}\"\"\", 0, False\r\n",
            web = web_cmd.display(),
        );
        fs::create_dir_all(&startup).map_err(|error| {
            log::error!("[dsh 自启(win)] 创建启动文件夹失败: {}", error);
            trf(
                "Failed to create directory: {error}",
                &[("error", error.to_string())],
            )
        })?;
        fs::write(&vbs, vbs_body).map_err(|error| {
            log::error!("[dsh 自启(win)] 写自启 vbs 失败: {}", error);
            trf(
                "Failed to write {path}: {error}",
                &[
                    ("path", vbs.display().to_string()),
                    ("error", error.to_string()),
                ],
            )
        })?;
    } else {
        let _ = fs::remove_file(&vbs);
        let _ = fs::remove_file(&web_cmd);
    }
    Ok(())
}
#[cfg(target_os = "linux")]
pub(crate) fn autostart_impl(enabled: bool) -> Result<(), String> {
    let home = config::home_dir()?;
    let units_dir = home.join(".config/systemd/user");
    let autostart_dir = home.join(".config/autostart");
    let dsh = dsh_dir()?;
    let web_script = dsh.join("start-web.sh");
    let legacy_proxy_script = dsh.join("start-proxy.sh");
    let web_unit = units_dir.join("dsh-remote-web.service");
    let legacy_proxy_unit = units_dir.join("dsh-remote-proxy.service");
    let web_desktop = autostart_dir.join("dsh-remote-web.desktop");
    let legacy_proxy_desktop = autostart_dir.join("dsh-remote-proxy.desktop");

    let _ = Command::new("systemctl")
        .args(["--user", "disable", "--now", "dsh-remote-proxy.service"])
        .output();
    let _ = fs::remove_file(&legacy_proxy_unit);
    let _ = fs::remove_file(&legacy_proxy_desktop);
    let _ = fs::remove_file(&legacy_proxy_script);
    kill_by_pattern("loopback-proxy.js");

    if enabled {
        let node = resolve_node_bin()?;
        let dsh_bin = resolve_dsh_bin()?;
        let ts = tailscale_path().ok_or_else(|| tr("Tailscale is not installed"))?;
        let login = resolve_tailscale_login(&ts)?;
        let fqdn = resolve_fqdn().unwrap_or_default();
        let auth = resolve_auth_config()?;
        fs::write(
            &web_script,
            render_start_web(&node, &dsh_bin.display().to_string(), &fqdn, &login, &auth),
        )
        .map_err(|error| {
            log::error!("[dsh 自启(linux)] 写启动脚本失败: {}", error);
            trf(
                "Failed to write {path}: {error}",
                &[
                    ("path", web_script.display().to_string()),
                    ("error", error.to_string()),
                ],
            )
        })?;

        if systemd_user_available() {
            fs::create_dir_all(&units_dir).map_err(|error| {
                log::error!("[dsh 自启(linux)] 创建 systemd 目录失败: {}", error);
                trf(
                    "Failed to create directory: {error}",
                    &[("error", error.to_string())],
                )
            })?;
            let unit = format!(
                "[Unit]\nDescription=DeepSeek Harness web (Tailscale authorization)\nAfter=network.target\n\n[Service]\nType=simple\nExecStart=/bin/sh {script}\nRestart=on-failure\n\n[Install]\nWantedBy=default.target\n",
                script = sh_quote(&web_script.display().to_string()),
            );
            fs::write(&web_unit, unit).map_err(|error| {
                log::error!("[dsh 自启(linux)] 写 systemd unit 失败: {}", error);
                trf(
                    "Failed to write {path}: {error}",
                    &[
                        ("path", web_unit.display().to_string()),
                        ("error", error.to_string()),
                    ],
                )
            })?;
            let _ = Command::new("systemctl")
                .args(["--user", "daemon-reload"])
                .output();
            let output = Command::new("systemctl")
                .args(["--user", "enable", "dsh-remote-web.service"])
                .output()
                .map_err(|error| {
                    log::error!("[dsh 自启(linux)] 执行 systemctl enable 失败: {}", error);
                    trf(
                        "Cannot enable systemd unit: {error}",
                        &[("error", error.to_string())],
                    )
                })?;
            if !output.status.success() {
                let err = trf(
                    "Cannot enable systemd unit: {error}",
                    &[(
                        "error",
                        String::from_utf8_lossy(&output.stderr).trim().to_string(),
                    )],
                );
                log::error!("[dsh 自启(linux)] 启用 systemd 服务失败: {}", err);
                return Err(err);
            }
            let _ = fs::remove_file(&web_desktop);
        } else {
            fs::create_dir_all(&autostart_dir).map_err(|error| {
                log::error!("[dsh 自启(linux)] 创建 autostart 目录失败: {}", error);
                trf(
                    "Failed to create directory: {error}",
                    &[("error", error.to_string())],
                )
            })?;
            fs::write(
                &web_desktop,
                render_desktop_entry(
                    "DeepSeek Harness web (Tailscale authorization)",
                    &web_script,
                ),
            )
            .map_err(|error| {
                log::error!("[dsh 自启(linux)] 写 .desktop 失败: {}", error);
                trf(
                    "Failed to write {path}: {error}",
                    &[
                        ("path", web_desktop.display().to_string()),
                        ("error", error.to_string()),
                    ],
                )
            })?;
            let _ = fs::remove_file(&web_unit);
        }
    } else {
        let _ = Command::new("systemctl")
            .args(["--user", "disable", "dsh-remote-web.service"])
            .output();
        let _ = Command::new("systemctl")
            .args(["--user", "daemon-reload"])
            .output();
        let _ = fs::remove_file(&web_unit);
        let _ = fs::remove_file(&web_desktop);
        let _ = fs::remove_file(&web_script);
    }
    Ok(())
}
#[cfg(target_os = "linux")]
pub(crate) fn systemd_user_available() -> bool {
    match Command::new("systemctl")
        .args(["--user", "is-system-running"])
        .output()
    {
        Ok(o) => {
            let out = String::from_utf8_lossy(&o.stdout).to_lowercase();
            o.status.success()
                || out.contains("running")
                || out.contains("degraded")
                || out.contains("starting")
        }
        Err(_) => false,
    }
}

/// XDG autostart .desktop 文件（Linux 兜底自启机制）
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub(crate) fn render_desktop_entry(name: &str, script: &Path) -> String {
    format!(
        "[Desktop Entry]\nType=Application\nName={name}\nComment=DeepSeek Harness remote access via Tailscale\nExec=/bin/sh {script}\nTerminal=false\nX-GNOME-Autostart-enabled=true\nNoDisplay=true\n",
        name = name,
        script = sh_quote(&script.display().to_string()),
    )
}
